version: '3.8'

services:
  llm_app:
    build: .
    container_name: llm_app_container
    stdin_open: true # Открывает стандартный ввод
    tty: true        # Включает поддержку терминала
    volumes:
      - ./data:/app/data/